<a href="https://colab.research.google.com/github/PaulNjinu254/Implementing-Matrix-Multipliation/blob/main/Implementing_Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# implementation using the python operators
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
result = np.matmul(a_ndarray, b_ndarray)
print("the solution using np.matmul is: \n",result)
result_1 = np.dot(a_ndarray, b_ndarray)
print("the solution using np.dot is: \n",result_1)
result_2 = a_ndarray @ b_ndarray
print("the solution while using @ is: \n",result_2)

# implementation of the hand method by coding
def matmul_scratch(a, b):
    result = np.zeros((a.shape[0], b.shape[1]))  # 結果を格納するための0行列を作成
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]
    return result

scratch_result = matmul_scratch(a_ndarray, b_ndarray)
print("the solution to the implementation of the hand method by coding is: \n",scratch_result)

# checking if the calculation is defined
def is_multiplicable(a, b):
    if a.shape[1] != b.shape[0]:
        print("Cannot compute matrix product. The number of columns and rows do not match.")
        return False
    return True

if is_multiplicable(a_ndarray, b_ndarray):
    print("the matrices are multipicable and the answer is:\n",(np.matmul(a_ndarray, b_ndarray)))

the solution using np.matmul is: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
the solution using np.dot is: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
the solution while using @ is: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
the solution to the implementation of the hand method by coding is: 
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
the matrices are multipicable and the answer is:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
