<a href="https://colab.research.google.com/github/PaulNjinu254/Implementing-Matrix-Multipliation/blob/main/Implementing_Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Original matrices
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 1. Manual calculation explanation
def explain_matrix_multiplication(a, b):
    """Explain how matrix multiplication works manually"""
    print("\n=== Manual Calculation Explanation ===")
    print("Matrix multiplication involves multiplying rows of the first matrix")
    print("with columns of the second matrix and summing the products.")
    print("For each element in the result matrix at position (i,j):")
    print("result[i,j] = sum(a[i,k] * b[k,j] for k in range(a.shape[1]))")
    print("\nLet's calculate the first element (0,0) as an example:")
    print(f"result[0,0] = ({a[0,0]}*{b[0,0]}) + ({a[0,1]}*{b[1,0]}) + ({a[0,2]}*{b[2,0]})")
    print(f"            = {a[0,0]*b[0,0]} + {a[0,1]*b[1,0]} + {a[0,2]*b[2,0]}")
    print(f"            = {a[0,0]*b[0,0] + a[0,1]*b[1,0] + a[0,2]*b[2,0]}")
    print("\nThis process is repeated for all elements in the result matrix.\n")

explain_matrix_multiplication(a_ndarray, b_ndarray)

# 2. Survey considerations
print("=== Survey Considerations ===")
print("Based on my understanding of linear algebra:")
print("- Matrix multiplication is fundamental in many applications")
print("- Understanding the manual process helps debug numerical issues")
print("- The dot product implementation is efficient but knowing the")
print("  underlying process is valuable for algorithm development\n")

# 3. Implementation using Python operators (original)
print("=== Built-in Implementations ===")
result = np.matmul(a_ndarray, b_ndarray)
print("Solution using np.matmul:\n", result)
result_1 = np.dot(a_ndarray, b_ndarray)
print("\nSolution using np.dot:\n", result_1)
result_2 = a_ndarray @ b_ndarray
print("\nSolution using @ operator:\n", result_2)

# 4. Scratch implementation with error handling
def matmul_scratch(a, b):
    """Manual matrix multiplication with error handling"""
    try:
        if a.shape[1] != b.shape[0]:
            raise ValueError("Matrix dimensions incompatible for multiplication")

        result = np.zeros((a.shape[0], b.shape[1]))
        print("\n=== Scratch Calculation Steps ===")

        for i in range(a.shape[0]):
            for j in range(b.shape[1]):
                print(f"\nCalculating element ({i},{j}):")
                sum_products = 0
                for k in range(a.shape[1]):
                    product = a[i,k] * b[k,j]
                    sum_products += product
                    print(f"  + {a[i,k]}*{b[k,j]} = {product} (sum: {sum_products})")
                result[i,j] = sum_products
                print(f"Final value for ({i},{j}): {sum_products}")

        return result

    except ValueError as e:
        print(f"Error: {e}")
        return None
    except Exception as e:
        print(f"Unexpected error: {e}")
        return None

print("\n=== Scratch Implementation ===")
scratch_result = matmul_scratch(a_ndarray, b_ndarray)
if scratch_result is not None:
    print("\nFinal result from scratch implementation:\n", scratch_result)

# 5. Matrix transposition and product calculation
def matmul_with_transpose(a, b):
    """Matrix multiplication using transpose for efficiency"""
    try:
        if a.shape[1] != b.shape[0]:
            raise ValueError("Matrix dimensions incompatible for multiplication")

        print("\n=== Transpose Method ===")
        b_transpose = b.T
        print("Transposed matrix B:\n", b_transpose)

        result = np.zeros((a.shape[0], b_transpose.shape[0]))

        for i in range(a.shape[0]):
            for j in range(b_transpose.shape[0]):
                result[i,j] = np.dot(a[i,:], b_transpose[j,:])
                print(f"Element ({i},{j}): dot product of row {i} of A and row {j} of B.T = {result[i,j]}")

        return result

    except ValueError as e:
        print(f"Error: {e}")
        return None
    except Exception as e:
        print(f"Unexpected error: {e}")
        return None

transpose_result = matmul_with_transpose(a_ndarray, b_ndarray)
if transpose_result is not None:
    print("\nResult using transpose method:\n", transpose_result)

# 6. Comprehensive error checking
def check_and_multiply(a, b):
    """Comprehensive matrix multiplication with error checking"""
    print("\n=== Comprehensive Check ===")
    if not isinstance(a, np.ndarray) or not isinstance(b, np.ndarray):
        print("Error: Both inputs must be numpy arrays")
        return None

    if a.ndim != 2 or b.ndim != 2:
        print("Error: Both matrices must be 2-dimensional")
        return None

    if a.shape[1] != b.shape[0]:
        print(f"Error: Cannot multiply {a.shape} matrix with {b.shape} matrix")
        print("Number of columns in first matrix must match number of rows in second")
        return None

    print("Matrices are compatible for multiplication")
    result = a @ b
    print("Multiplication result:\n", result)
    return result

# Test with valid matrices
print("\nTesting with valid matrices:")
check_and_multiply(a_ndarray, b_ndarray)

# Test with invalid matrices
invalid_matrix = np.array([[1, 2], [3, 4]])
print("\nTesting with invalid matrices:")
check_and_multiply(a_ndarray, invalid_matrix)


=== Manual Calculation Explanation ===
Matrix multiplication involves multiplying rows of the first matrix
with columns of the second matrix and summing the products.
For each element in the result matrix at position (i,j):
result[i,j] = sum(a[i,k] * b[k,j] for k in range(a.shape[1]))

Let's calculate the first element (0,0) as an example:
result[0,0] = (-1*0) + (2*0) + (3*2)
            = 0 + 0 + 6
            = 6

This process is repeated for all elements in the result matrix.

=== Survey Considerations ===
Based on my understanding of linear algebra:
- Matrix multiplication is fundamental in many applications
- Understanding the manual process helps debug numerical issues
- The dot product implementation is efficient but knowing the
  underlying process is valuable for algorithm development

=== Built-in Implementations ===
Solution using np.matmul:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Solution using np.dot:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Solution using 